/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.mavenproject1;


import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import static com.mongodb.client.model.Indexes.descending;
import org.bson.Document;
import org.bson.types.ObjectId;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author khanny
 */
public class JOLogs extends javax.swing.JFrame {
    
    

    /** Creates new form JOLogs */
    public JOLogs() {
        initComponents();
        loadData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job Type", "Job Code", "Client Name", "Address", "Contact", "Concern", "Team Leader", "Transportation", "Date Issued", "Date Due"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
       private void loadData() {
        String uri = "mongodb+srv://khadeem:lenin_JO@clusterleninjo.divpuaq.mongodb.net/?retryWrites=true&w=majority&appName=ClusterLeninJO";
        try (com.mongodb.client.MongoClient mongoClient = MongoClients.create(uri)) {
            MongoDatabase database = mongoClient.getDatabase("LeninJobOrder");
            MongoCollection<Document> collection = database.getCollection("solutionsClient");

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            try (MongoCursor<Document> cursor = collection.find().iterator()) {
                if (!cursor.hasNext()) {
                    System.out.println("No documents found in the collection.");
                }
                while (cursor.hasNext()) {
                    Document doc = cursor.next();
                    System.out.println("Document: " + doc.toJson());  // Debug: Print each document

                    String jobType = doc.getString("job_type");
                    String jobCode = doc.getString("job_code");
                    String clientName = doc.getString("client_name");
                    String address = doc.getString("address");
                    String contact = doc.getString("contact");
                    String concern = doc.getString("concern");
                    String teamLeader = doc.getString("team_leader");
                    String transportation = doc.getString("transportation");
                    String dateIssued = doc.getString("date_issued");
                    String dateDue = doc.getString("date_due");
                    String status = doc.getString("status");

                    model.addRow(new Object[] { jobType, jobCode, clientName, address, contact, concern, teamLeader, transportation, dateIssued, dateDue, status });

                }
            }
           

            
        } catch (Exception e) {
            Logger.getLogger(JOLogs.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error: " + e.getMessage());  // Debug: Print the exception message
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new JOLogs().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
